version: "3.3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    networks:
      ubicomp:
    env_file:
      - ./influx2.env
    volumes:
      - influxdata:/var/lib/influxdb2
    ports:
      - "8086:8086"
  grafana:
    container_name: grafana
    ports:
      - 3000:3000
    image: grafana/grafana:latest
    networks:
      ubicomp:
    depends_on:
      - influxdb
    links:
      - influxdb:influxdb
    volumes:
      - grafanadata:/var/lib/grafana
      - grafana-log:/var/log/grafana
  mqtt:
    container_name: mqtt
    hostname: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    networks:
      ubicomp:
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1884:1884
      - 9001:9001
  manager:
    image: emqx/ekuiper-manager:1.8.0 
    container_name: ekuiper-manager
    networks:
      ubicomp:  
    ports:
      - 9082:9082
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
  ekuiper:
    container_name: ekuiper
    hostname: ekuiper
    image: lfedge/ekuiper:1.8.0
    networks:
      ubicomp:
    ports:
      - 9081:9081
      - 127.0.0.1:20498:20498
    environment:
      MQTT_SOURCE__DEFAULT__SERVERS: "tcp://mqtt:1884"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    restart: unless-stopped
    user: root
    volumes:
      - /tmp/data:/kuiper/data
      - /tmp/log:/kuiper/log
  iot-app:
    container_name: iot-app
    build:
      context: ./app
    image: iotapp
    networks:
      ubicomp:
    privileged: true
    depends_on:
      - mqtt
      - influxdb

volumes:
  influxdata:
  grafanadata:
  grafana-log:

networks:
  ubicomp: